# Generated by Django 4.2.7 on 2025-12-01 01:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
            },
        ),
        migrations.AlterModelOptions(
            name="userquizattempt",
            options={
                "ordering": ["-completed_at"],
                "verbose_name": "User Quiz Attempt",
                "verbose_name_plural": "User Quiz Attempts",
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="order",
            field=models.IntegerField(default=0, help_text="Display order within the question"),
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.IntegerField(default=0, help_text="Display order within the quiz"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether the quiz is available for users to take"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False, help_text="Whether this is a correct answer"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                help_text="The question this answer belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="quiz_api.question",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(help_text="Answer text (max 500 characters)", max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="points",
            field=models.IntegerField(
                default=1,
                help_text="Points awarded for correct answer (1-100)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single", "Single Answer"),
                    ("multi", "Multiple Answer"),
                    ("select_words", "Select Words"),
                ],
                help_text="Type of question",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                help_text="The quiz this question belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz_api.quiz",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(help_text="The question text"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the quiz was created"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(help_text="Detailed description of the quiz"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(help_text="Quiz title (max 200 characters)", max_length=200),
        ),
        migrations.AlterField(
            model_name="userquizattempt",
            name="completed_at",
            field=models.DateTimeField(auto_now_add=True, help_text="When the quiz was completed"),
        ),
        migrations.AlterField(
            model_name="userquizattempt",
            name="quiz",
            field=models.ForeignKey(
                help_text="The quiz that was attempted",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="quiz_api.quiz",
            ),
        ),
        migrations.AlterField(
            model_name="userquizattempt",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Score as a percentage (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userquizattempt",
            name="user",
            field=models.ForeignKey(
                help_text="The user who attempted the quiz",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["question", "is_correct"], name="quiz_api_an_questio_14849e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["quiz", "order"], name="quiz_api_qu_quiz_id_186fdd_idx"),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(fields=["-created_at"], name="quiz_api_qu_created_053bc2_idx"),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(fields=["is_active"], name="quiz_api_qu_is_acti_0d88f2_idx"),
        ),
        migrations.AddIndex(
            model_name="userquizattempt",
            index=models.Index(
                fields=["user", "-completed_at"], name="quiz_api_us_user_id_a4f551_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userquizattempt",
            index=models.Index(
                fields=["quiz", "-completed_at"], name="quiz_api_us_quiz_id_ecd6ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userquizattempt",
            index=models.Index(fields=["-completed_at"], name="quiz_api_us_complet_f89f74_idx"),
        ),
    ]
