# Generated by Django 4.2.7 on 2025-12-01 09:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_api", "0002_alter_answer_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (max 100 characters)", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the category"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the category was created"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name (max 50 characters)", max_length=50, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the tag was created"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="explanation",
            field=models.TextField(blank=True, help_text="Optional explanation for this answer"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="difficulty_level",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                help_text="Difficulty level of the quiz",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="time_limit_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="Time limit in minutes (1-180, optional)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userquizattempt",
            name="answers_data",
            field=models.JSONField(
                default=dict, help_text="JSON data storing user's answers and correctness"
            ),
        ),
        migrations.AddField(
            model_name="userquizattempt",
            name="started_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="When the quiz was started"
            ),
        ),
        migrations.AddField(
            model_name="userquizattempt",
            name="time_taken_seconds",
            field=models.IntegerField(
                blank=True, help_text="Time taken to complete the quiz in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary category for this quiz",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizzes",
                to="quiz_api.category",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags associated with this quiz",
                related_name="quizzes",
                to="quiz_api.tag",
            ),
        ),
    ]
